### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Shadowless99** [RobertSkalko/Mine-and-Slash#1]
Hello,

first off, I would like to say, that i really love your mod. I think it's very innovative aside from everything else that is offered moding wise.

Now that i said that, following things struck me:

* On a server i get a lot of nullpointer exceptions, i assume your mod is not ready for a server?
* Cobwebs cannot be cut with swords from your mod
* I'd love to see a config option for starting level and level distance on a per dimension base.
* One thing that would be really cool, because it would make interaction with other mods better is when crafting gear ie. diamond sword, it should get itemlevel of your char and random rolls from your mod.
* Any chance of cheating in gear with a special itemlevel for testing purposes?

I had some other problems with like no fall damage, almost no void damage, and other things like that, but that seems fixed with the latest update.
If anything else comes to my mind, I hope its ok to send it to you here on github.

Thank you for this great mod,

Greetings Shadowless99

**Comment by RobertSkalko** [comment]
Thanks for the compliments! Now about your problems

* ill check ur logs for nullpointers
* weapons in my mod are actually derived from tools, because swords are by nature aoe but i wanted aoe to be a special thing of other weapons.
* per dimension level configs.. hmm seems possible. but for now i only know how to do for vanilla ones
* this part is insanely difficult, at least i don't see an easy way to accomplish it. I could try to identify a weapon somehow.. but it breaks the balance of the mod so maybe as a config when i find a way to do it
* there are commands and they should have good descriptions with /help (name). they are givegear, giveunique, givespell, givemap. 

Anyway in case some modder knows to help, here's my dillema with giving vanilla items my mod's stats.

Say i set it so any item crafted with the name "sword" in it gets sword stats based on the player who crafted it. 

But what if there's a helmet called swordman's helmet and it get sword stats? Insanely op and balance breaking issue.. Maybe i could only check java classes, check if it's an instanceof ItemSword.

There's also the problem of adding a default basic attack for other mod's weapons, tho that part should be easier.

**Comment by cdcp998** [comment]
> 谢谢你的称赞！现在关于你的问题
> 
> * 生病检查你的日志为nullpointers
> * 我的mod中的武器实际上来自工具，因为剑本质上是aoe但我想让aoe成为其他武器的特殊之物。
> * 每个维度级配置..嗯似乎可能。但是现在我只知道如何做香草的
> * 这部分是非常困难的，至少我看不到一个简单的方法来实现它。我可以尝试以某种方式识别武器..但它打破了mod的平衡所以可能作为配置当我找到一种方法来做它
> * 有命令，他们应该有/ help（名称）的良好描述。他们是Givegear，giveunique，givepell，givemap。
> 
> 无论如何，如果一些modder知道帮助，这里是我的dillema与给我的mod的统计数据香草项目。
> 
> 假设我设置它所以任何用“剑”这个名字制作的项目都会根据制作它的玩家获得剑的统计数据。
> 
> 但是，如果有一个名为剑士头盔的头盔并获得剑的统计数据呢？疯狂操作和平衡破坏问题..也许我只能检查java类，检查它是否是ItemSword的实例。
> 
> 还有为其他mod的武器添加默认基本攻击的问题，那部分应该更容易。

https://github.com/TheXFactor117/Loot-Slash-Conquer

> Thanks for the compliments! Now about your problems
> 
> * ill check ur logs for nullpointers
> * weapons in my mod are actually derived from tools, because swords are by nature aoe but i wanted aoe to be a special thing of other weapons.
> * per dimension level configs.. hmm seems possible. but for now i only know how to do for vanilla ones
> * this part is insanely difficult, at least i don't see an easy way to accomplish it. I could try to identify a weapon somehow.. but it breaks the balance of the mod so maybe as a config when i find a way to do it
> * there are commands and they should have good descriptions with /help (name). they are givegear, giveunique, givespell, givemap.
> 
> Anyway in case some modder knows to help, here's my dillema with giving vanilla items my mod's stats.
> 
> Say i set it so any item crafted with the name "sword" in it gets sword stats based on the player who crafted it.
> 
> But what if there's a helmet called swordman's helmet and it get sword stats? Insanely op and balance breaking issue.. Maybe i could only check java classes, check if it's an instanceof ItemSword.
> 
> There's also the problem of adding a default basic attack for other mod's weapons, tho that part should be easier.

You can refer to https://github.com/TheXFactor117/Loot-Slash-Conquer equipment support

**Comment by RobertSkalko** [comment]
I think most of the suggestions were implemented already, closing.
