### ISSUE TITLE
Some ideas for improvements

### ISSUE THREAD

**Issue by Paladin1979** [RobertSkalko/Mine-and-Slash#90]
Hi, I'm playing mine and slash as part of the World of Dragons modpack; I'm aware that this is 1.12 and supported by AzureZhen, but I have a couple of suggestions. I've posted these in the WoD issue tracker, I'm copying them here as well. It might be that some of this is in 1.14 already; I had no luck using a search through the issues for these subjects but if I made an oversight I apologize in advance.

So, here comes:
- I would not let animals give mine and slash xp or loot. Currently, a lot of my xp comes from slaughtering cows and squid, and actually some of my better gear too. This feels very wrong and exploitable. (currently animals give half the xp of hostile mobs) Another option I thought of would be to make the xp reward always based on a level 1 mob, which means slaughtering animals would help getting past the first few levels, but would hardly be worth it after (not in terms of xp, anyway). I would drop the loot in any case.
- Instead of penalizing low-level players for making high-level kills (if I saw it correctly, xp is cut off at what a mob of the player's level would give), I would do it the other way around, i.e. don't give a player xp for killing a mob 5(?) levels lower than him/herself. Diablo and WoW have quite sophisticated scaling systems for the xp mobs give to players of lower and higher levels that can be used as examples; I think a simple cutoff is too crude.
- If a player kills a mob of a higher level than himself (more power to him if he can manage it), change the loot dropped to the level of the player (I think this is what Diablo does). I found it very frustrating that, although I was very much capable of killing level 20 mobs, that I had to go back to a level 10 area to get gear I could use. There is something nice about having a legendary level 23 sword waiting for me, but the frustration of not having usable gear now is worse.
- Any options for bridging the gap until adventure maps start dropping at level 20 would be welcome. (This is the main reason I went to a level 20 area to set up my base) - I actually CAN use the adventure maps that drop every once in a while. I do not really understand why this limitation is there (i.e. why not drop level 1 adventure maps?)
- In the WoD modpack, there's an exploit where a summoned zombie from electroblob's gives full xp to the player who killed it - also there is a wish to discourage people from camping mob spawners. I think it would be better if summoned mobs (from other modpacks) and mobs from spawners yield no xp and M&S loot at all, but instead have the summoner/spawner yield more - rather than discouraging camping, this would encourage breaking the spawner (which, psychologically, works better). Mob spawners might need to get a rarity.
- I think the compatibility with crafted weapons needs to be improved. Currently either (vanilla) crafted weapons don't do squat (which is frustrating) or they do way too much (when set as compatible). as an example of the former - after leveling, my best bet to get a decent sword is to craft 10 stone swords and use the best one. It is also really easy to obtain M&S ores that way - craft a ton of stone swords and chuck them through the salvage table. The M&S loot can be better but drops so rarely for a specific level that 9 times out of 10 this works best. Durability of a compatible stone sword is MUCH lower but I can live with that.

Some personal dislikes that I just want to give as feedback (but the stuff above is more important to me):
- I think the random items are TOO random. Spells are worst, e.g. a spell of healing has both a huge range for its mana cost AND a huge range on its effect, so the best rolled spell is nearly 4 times as good as the worst. It's not as bad for weapons but still too random for my tastes. I would make the random range much smaller (a "bad" roll being at least 75% as good as a perfect roll) (for diablo this is not as bad because you're killing mobs non-stop, and as a consequence have a much higher amount of loot. this is not as easy to do in minecraft.)
- I don't like the energy system. I've gotten used to it, it works, but in my opinion it doesn't add something as a replacement of the existing attack speed mechanism that minecraft itself has. My suggestion there would be to get rid of it and use the existing mechanism.
- It is not clear to me why anyone would ever use an axe or hammer (which costs 8.5 or even 10 energy to use) instead of a sword (which costs 3 energy to use) while the damage is similar. if axes had potentially two times the damage of a sword it might make sense, but to my understanding the damage range for a sword and axe are the same. It feels like a flavored version of the randomness on spells. My suggestion would be to increase the damage of axes and hammers proportionally to their slowness, OR to add some unique abilities to them to make them stand out and be a real choice. It looks like hammers are AOE (have I got that right?) but currently it doesn't do it for me.

**Comment by RobertSkalko** [comment]
* you can already set animals to not give any xp or loot
* "I think a simple cutoff is too crude." it's not simple, it's based on the difference of lvls. And no, i'm not changing this 
* same thing, i'm not going to reward players who kill mobs of way different lvl
* configurable once again, i set it at 20 so new players who didnt even build a map device won't get maps as soon as they spawn in a world. Also incentive to lvl.
* if mods with pet spawns have unique mob ids, you can set their xp and loot to 0 already. Otherwise it'd require manual compatibility for every mod unless they all use some same thing. Also, you can use a mod that makes spawners destroy themselves after x spawns.
* compatible items are MODPACK'S RESPONSIBILITY. By default they don't exist. I can't balance another person's modpack.

* no, i like rng
* "I don't like the energy system. I've gotten used to it, it works, but in my opinion it doesn't add something as a replacement of the existing attack speed mechanism that minecraft itself has"
energy adds a whole set of stats and build options, alongside balancing opportunities for weapons and limiting dps. You can ofc disable it by setting your base stats to max numbers.
* this is already like that. Swords are low dmg, high energy efficiency, axes are high dmg, low energy efficiency.

All in all, this seems like a combination of modpack config problems and your own personal dislikes. 
It's also possible the compatible items are the default mod option that azure recently introduced though.

I don't know how many times i said to not make compatible items salvagable and to not make wooden swords able to be mythic rarity, but people don't really listen.
